### PR TITLE
Modular actions (deploy and publish)

### PR DESCRIPTION
**Pull request by arjun-1**
Add the following specific actions:
* `build-and-publish/dockerfile`: builds and publishes an image from dockerfile
* `deploy/kustomize` and `deploy-dryrun/kustomize`: deploys and deploys dry-run a kustomize resource directory.

The actions are used in the https://github.com/kaizo-com/kafka-connect project.

Note that ideally, the actions could be enriched with authentication logic. That is however not yet possible, due to limitations of github actions (see https://github.com/actions/runner/issues/646). It is expected in the near future though.

### CODE REVIEW

**Comment by agemooij** [comment]
@arjun-1 is this Pr still required no that we have the Helm action merged and in use?
If so, could you perhaps update it to only contain the bits not already covered by the Helm action?

**Comment by arjun-1** [comment]
> @arjun-1 is this Pr still required no that we have the Helm action merged and in use?
> If so, could you perhaps update it to only contain the bits not already covered by the Helm action?

@agemooij I would say it is still required since the kafka-connect pipeline currently relies on this branch (through Kustomize). The only 2 parts contained in this PR are:
* Ability to build and publish given a Dockerfile
* Ability to deploy using a Kustomize resource directory
which are not covered in the HELM action. Of course, once we migrate kafka-connect to HELM (or build or own BQ connector) these actions would become irrelevant, but only then I'd say.

**Comment by agemooij** [comment]
OK. Then I'll leave it up to you and just approve so you can resolve the conflict and merge. I'd prefer if we didn't wait too long with moving to the Helm-based deployment and I think that in the long run we should replace the kafka-connect with a more flexible custom implementation based on akka streams and alpakka, with a simple stream started per required export.

**Review by agemooij — APPROVED** [review]

**Comment by agemooij** [comment]
@arjun-1 reminder to fix and merge this PR

**Comment by agemooij** [comment]
@arjun-1 AFAIK we can close this PR, now that we no longer run Kafka connect. Can you please confirm?

**Comment by arjun-1** [comment]
@agemooij we could have used potentially the deploy from dockerfile for agent-scorecard-module, but the functionality is already present now in the agent-scorecard-module repo. So this PR can indeed be closed

**Pull request closed without merging**
