### PR TITLE
Upgraded versions of Helm and kubectl

### PR DESCRIPTION
**Pull request by agemooij**
### Description
I noticed that the versions for kubectl and Helm were quite old. The version of kubectl used would soon be lower than the version we use for our cluster.

I upgraded the Dockerfile to always install the latest stable kubectl, which is currently v1.21.x
I also upgraded Helm to the latest release.

### CODE REVIEW

**Review by SvenvDam — APPROVED** [review]
LGTM 👍

**Comment by agemooij** [comment]
@SvenvDam I guess we will have to release this as v2 and then slowly switch all the CD jobs to use it, right?

**Comment by SvenvDam** [comment]
@agemooij from what I can see this should be non-breaking. So we can also merge and force-tag the latest commit on master as `helm/v1`. Then all users of this action will directly pick this up.

**Comment by agemooij** [comment]
@SvenvDam OK, good point. I'll use a commit hash to try it out on one build before force-tagging then.

**Pull request merged**
